# Generated by Django 5.0.3 on 2024-05-13 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categoria', '0002_remove_categorias_categoria_colchon_and_more'),
        ('Transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='id_Categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Categoria.categorias'),
        ),
    ]
