# Generated by Django 5.0.3 on 2024-03-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_rename_name_usermodel_userame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='userame',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
