# Generated by Django 5.0.3 on 2024-05-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoria_gastos_fijos', models.CharField(default='Gastos Fijos', editable=False, max_length=255)),
                ('Categoria_gastos_variables', models.CharField(default='Gastos Variables', editable=False, max_length=255)),
                ('Categoria_ahorro', models.CharField(default='Ahorro', editable=False, max_length=255)),
                ('Categoria_Colchon', models.CharField(default='Colchon', editable=False, max_length=255)),
            ],
        ),
    ]
