# Generated by Django 5.0.3 on 2024-05-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categoria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='Categoria_Colchon',
        ),
        migrations.RemoveField(
            model_name='categorias',
            name='Categoria_ahorro',
        ),
        migrations.RemoveField(
            model_name='categorias',
            name='Categoria_gastos_fijos',
        ),
        migrations.RemoveField(
            model_name='categorias',
            name='Categoria_gastos_variables',
        ),
        migrations.AddField(
            model_name='categorias',
            name='Categoria',
            field=models.CharField(default='Gastos Fijos', max_length=255),
        ),
    ]
