# Generated by Django 5.0.3 on 2024-03-15 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['-fecha']},
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
