# Generated by Django 5.0.3 on 2024-03-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicaciones', '0002_alter_publicacion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='image',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
