# Generated by Django 5.0.3 on 2024-03-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicaciones', '0003_remove_publicacion_image_publicacion_imagen_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
