# Generated by Django 5.0.3 on 2024-03-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicaciones', '0004_remove_publicacion_imagen_url_publicacion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
