# Generated by Django 5.0.3 on 2024-03-21 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publicaciones', '0005_alter_publicacion_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='image',
        ),
    ]
