# Generated by Django 5.0.3 on 2024-03-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicaciones', '0006_remove_publicacion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
